### ISSUE TITLE
Crash with Vanilla Hammers

### ISSUE THREAD

**Issue by shadowfacts** [AlexIIL/LibMultiPart#27] opened 2021-03-15 02:55 UTC
The game crashes rendering block outlines when LMP is installed and holding a hammer from [Vanilla Hammers](https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers). Vanilla Hammers modifies the outline shape to be a 3x3 set of blocks while holding a hammer, so I'd guess there's a mixin conflict.

https://gist.github.com/shadowfacts/95385bebb56309133867b6a84244aaba

**Comment by AlexIIL** [comment] 2021-03-15 03:34
Thanks for reminding me! This must have slipped my mind, since I thought that I would release the fix for this ["tomorrow"](https://github.com/AlexIIL/SimplePipes/issues/51#issuecomment-790239351), but that was 11 days ago :/

(Duplicate of #26).

**Closed as completed by AlexIIL** 2021-03-15 03:34 UTC

**Comment by AlexIIL** [comment] 2021-03-22 19:53
Okay, finally released in 0.5.0.
